services:
  taskflow-api:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # 注意看 command 这里的变化，加了一句替换阿里云源的代码
    command: sh -c "sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources && apt-get update && apt-get install -y build-essential python3 && npm install && npm rebuild sqlite3 --build-from-source && node server.js"